# Generated by Django 3.2.5 on 2021-07-17 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id_amostra', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo_amostra', models.CharField(max_length=255, unique=True)),
                ('metodo_de_coleta', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id_exame', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255, unique=True)),
                ('virus', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.IntegerField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente_exame_amostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_realizacao', models.DateTimeField(unique=True)),
                ('id_amostra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gerenciamentoPEA.amostra')),
                ('id_exame', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gerenciamentoPEA.exame')),
                ('id_paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gerenciamentoPEA.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='exame',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamentoPEA.paciente'),
        ),
    ]
