# Generated by Django 3.2.5 on 2021-07-17 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamentoPEA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente_exame_amostra',
            name='data_de_solicitacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
