# Generated by Django 3.2.5 on 2021-07-22 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamentoPEA', '0004_auto_20210719_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente_exame_amostra',
            name='id_amostra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamentoPEA.amostra'),
        ),
        migrations.AlterField(
            model_name='paciente_exame_amostra',
            name='id_exame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamentoPEA.exame'),
        ),
        migrations.AlterField(
            model_name='paciente_exame_amostra',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamentoPEA.paciente'),
        ),
    ]
